export const GENRES = [
  "Indie", "R&B", "Folk", "Ballad", "Jazz", "Acoustic", "Dance", "Rock", 
  "Punk", "Metal", "Soul", "Hip-Hop", "EDM", "Latin", "Reggae", "Funk", 
  "House", "Blues"
];

export const MOODS = [
  "조용한", "평온", "달콤한", "그루비", "중독성", "몽환적", "로맨틱", "따뜻한", 
  "감성적", "희망찬", "신나는", "밝은", "절제된", "잔잔한", "강렬한", "멜랑콜릭", "어반"
];

export const THEMES = [
  "사랑", "이별", "향수", "희망", "도시", "외로움", "두려움", "회상", "여유", 
  "분노", "우정", "여행", "자아성찰", "밤", "호기심", "퇴근", "시간", "자연", "성장"
];

export const BASE_PROMPTS = [
  "IndieR&B song, slow tempo around 82 BPM, Intro begins with minimal electric piano notes and subtle city ambience before warm Rhodes chords gradually enter, Soft fingerpicked acoustic guitar appears later in the arrangement, Smooth subtle bass line with extremely minimal brushed snare or nearly absent percussion, Warm acoustic guitar supporting the harmony, relaxed arrangement designed for reading, walking, and background listening, Mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, Vocal melody should stay in a comfortable mid-range with restrained storytelling vocal delivery, Warm natural mix with light reverb, no dramatic build-up, no explosive climax, Target song length strictly under 3 minutes, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieFolk song, slow tempo around 72–76 BPM, intro begins with gentle fingerpicked acoustic guitar alone before soft piano textures enter, warm acoustic guitar as the main instrument, subtle piano layers and soft bass support, extremely minimal percussion or nearly absent drums, relaxed arrangement suitable for reading, studying, and background listening, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained storytelling vocal delivery, warm natural mix with light reverb, reflective nostalgic mood, no dramatic build-up, no explosive climax, Target song length strictly under 3 minutes, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieR&B song with a calm and warm atmosphere suitable for background listening, slow tempo around 76–80 BPM, intro begins with gentle Rhodes chords followed by soft acoustic guitar layers, smooth subtle bass line, extremely minimal brushed snare or nearly absent percussion, relaxed arrangement designed for reading, studying, and walking, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained emotional delivery, warm natural mix with light reverb, peaceful reflective mood, no dramatic build-up, no explosive climax, Target song length strictly under 3 minutes, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieFolk song for a calm late-night reflective atmosphere, slow tempo around 72–76 BPM, intro begins with gentle piano notes followed by soft fingerpicked acoustic guitar, warm acoustic guitar as the main instrument, subtle piano textures and soft bass support, extremely minimal percussion or nearly absent drums, relaxed arrangement designed for reading, studying, and background listening, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained storytelling vocal delivery, warm natural mix with light reverb, reflective and peaceful mood, no dramatic build-up, no explosive climax, Target song length strictly under 3 minutes, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indieR&B pop, bright calm mood, 72–76 BPM, acoustic fingerpicking guitar lead, light piano accents, minimal brush drums, soft bass, airy ambient pads, intimate conversational vocal tone, no high notes, gentle reflective atmosphere, smooth flowing arrangement, warm natural mix, soft reverb, gentle fade-out ending, theme: quiet weekend afternoon noticing small changes in everyday life, Target song length strictly under 3 minutes, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indie pop, 76-80 BPM, warm acoustic guitar lead, light felt piano accents, gentle bass, minimal brush drums, airy ambient pads, reflective bus ride atmosphere, intimate soft vocal tone, no high notes, smooth flowing arrangement, warm sunset mood, natural mix, soft reverb, gentle fade-out ending, theme: watching the world through a bus window and quietly feeling a new beginning, Target song length strictly under 3 minutes, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indie folk, 74 BPM, warm acoustic guitar picking, light piano textures, gentle bass, minimal brush drums, calm evening walk atmosphere, reflective male vocal tone, storytelling delivery, no high notes, smooth flowing arrangement, warm natural mix, soft reverb, gentle fade-out ending, theme: pretending nothing changed while quietly realizing something did, Target song length strictly under 3 minutes, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Acoustic R&B with indie pop elements, bright and rhythmic groove, 92–98 BPM, warm acoustic guitar strumming, soft muted electric guitar riffs, Subtle bass groove, light percussive drums with rim clicks and soft snare, Gradual instrument layering from minimal guitar to full band in final chorus, Emotional but controlled vocal delivery (no excessive falsetto), Catchy and repetitive chorus hook, warm and uplifting atmosphere, Target song length strictly under 3 minutes, Intimate yet cinematic build-up, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, Restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Acoustic R&B with indie pop elements, bright and rhythmic groove, 92–98 BPM, warm acoustic guitar strumming, soft muted electric guitar riffs, Subtle bass groove, light percussive drums with rim clicks and soft snare, Gradual instrument layering from minimal guitar to full band in final chorus, Emotional but controlled vocal delivery (no excessive falsetto), Catchy and repetitive chorus hook, warm and uplifting atmosphere, Intimate yet cinematic build-up, final chorus with added harmonies and fuller drums, then gradually fading into a calm and quiet ending, Target song length strictly under 3 minutes, Intimate yet cinematic build-up, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, Restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Acoustic R&B ballad with indie pop elements, slow tempo around 74–80 BPM, Warm acoustic guitar arpeggios, soft piano or Rhodes textures, Smooth subtle bass line, very light brushed snare or minimal percussion, No dramatic build-up, no explosive climax, Mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, Warm natural mix with light reverb, no dramatic build-up, no explosive climax, Soft chest-dominant vocal tone, restrained and steady emotional delivery, Concise arrangement, no extended intro, no repeated extra chorus, tight structure, Smooth ending, Target song length strictly under 3 minutes",
  "Soulful Deep Vocals, Gritty Neo-soul, Gospel-inflected harmonies, Velvety Rich Texture, Melismatic Ad-libs, Jazzhop, Chillhop, Clean Chorus Electric Guitar, Soft Rhodes Piano, Mellow Walking Bassline, Steady Boom-bap Beat, Sophisticated Urban Vibe, 85 BPM, High Fidelity, Analog Warmth, Extended Length, Target song length strictly under 3 minutes",
  "Groovy indie pop with smooth rhythmic flow, 96 BPM, warm and intimate male vocal with calm confidence, clean electric guitar with muted funky strumming, round groovy bassline with subtle slides, tight minimal drums, soft snare, light 16th hi-hats, bright morning atmosphere with gentle sunlight feeling, uplifting but emotionally restrained, lyrics about starting over, first light, fresh air, taking steps forward, hopeful and steady mood, modern indie production, radio edit length under 3 minutes 40 seconds",
  "Minimal groovy indie pop with subtle emotional lift, 95 BPM, Warm intimate vocal, steady round bassline, Clean muted electric guitar rhythm, tight minimal drums with soft hi-hats, Calm but confident mood, theme of quiet growth and self-belief, No dramatic climax, smooth build in final chorus, Target song length strictly under 3 minutes, clean modern mix, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out,",
  "Soft urban indie pop, calm and reflective mood, 76–78 BPM, G major, Low, calm male vocal (hoodie persona), intimate and restrained, no belting, grounded delivery, Clean electric guitar with light reverb arpeggios (slightly more prominent than acoustic), Minimal brush drums steady from early verse, warm bass slightly, No glockenspiel, subtle city-night ambient texture, Arrangement steady and minimal, chorus slightly wider but not bigger in volume, Warm natural mix, soft reverb, gentle fade ending, Target song length strictly under 3 minutes, clean modern mix, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out",
  "Upbeat urban groovy indie pop, 110 BPM, cool confident vocal, driving funky bassline, muted rhythmic electric guitar, tight punchy drums with crisp hi-hats and claps, night drive city vibe, energetic but stylish mood, radio edit format, clear strong ending, length strictly under 3 minutes, no extended instrumental sections, do not loop endlessly",
  "Indie Groove, Jazzhop fusion, Clean electric guitar, Deep groovy bassline, Mid-tempo 92 BPM, Smooth Fender Rhodes, Crisp drums, No hiss, High-fidelity, Professional mixing, Atmospheric and Inspiring, Extended structure",
  "A bright, soft acoustic R&B pop with a sunny and cozy atmosphere, Features sweet, rhythmic acoustic guitar strumming and a mellow, organic Rhodes piano for a fresh and inviting mood, The tempo is 78 BPM, relaxed but with a light, walking-paced groove, Playful, melodic bassline and crisp finger snaps mixed with a soft shaker rhythm, Chorus blooms with airy, delicate string swells and subtle, high-register acoustic guitar harmonics that add a touch of elegance, The sound is clean, spacious, and high-fidelity, avoiding any sharp or metallic tones, The arrangement is minimal yet polished, easing into a gentle guitar and a soft, warm pad synth outro that leaves a cheerful, lingering sweetness, Romantic, sophisticated, sunny afternoon cafe vibe, instrumental, no explosive climax. Target song length strictly under 3 minutes, clean modern mix, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out"
];

export const MANDATORY_PROMPT_SUFFIX = "Restrained and steady emotional delivery, Target song length strictly under 3 minutes, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence";
